# Generated by Django 4.2.2 on 2025-02-03 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("journal", "0003_alter_diaryentry_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="owner",
            field=models.ForeignKey(
                help_text="Укажите автора записи",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
