# Generated by Django 4.2.2 on 2025-02-03 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("journal", "0004_alter_diaryentry_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="content",
            field=models.TextField(verbose_name="Запись в дневнике"),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Заголовок"),
        ),
    ]
